### PR TITLE
[Fix] FFMPEG locks up in some cases

### PR DESCRIPTION
**Pull request by bumbummen99**
Addresses #21

### CODE REVIEW

**Review by steffensiebert — COMMENTED** [review]
I will review the code later after pulling your changes and testing this issue, but after looking at the changed file, I think the timeout is too low. Currently 10ms default would kill YouTubeDL and Ffmeg after starting. Or do I miss something there?

**Comment by steffensiebert** [comment]
I've found a second issue:
YoutubeDL.cs L29: You call the Run method with the default timeout of 10s (10.000 ms). This will lead to the problem, that the download will stop after 10 secs. I dont think that anybody can download a southpark episode within 10 sec.

I have two options: First option is to set the timeout to a ridiculous high time, to prevent stopping the process with a slow internet connection. (You dont want this)
Second (and preferred) option is to use timeout 0 (only at YoutubeDL.cs Run call: L29) and use something like this at Executable.cs L98:
`


                bool processSuccess = false;
                if (timeout == 0)
                {
                    process.WaitForExit();
                    processSuccess = true;
                }
                else
                { 
                    processSuccess = process.WaitForExit(timeout);
                }

                bool success = processSuccess && outputWaitHandle.WaitOne(timeout) && errorWaitHandle.WaitOne(timeout);

`

**Comment by bumbummen99** [comment]
@KingStoffen Implemented the requested changes

**Comment by steffensiebert** [comment]
A Lambda check does not make sense, because WaitForExit() is a void method. Furthermore check the WaitOne() void method out, if this matches the case of your logic more.
I think of sth. like this:
`

            bool processSuccess = false;
            if (timeout <= 0)
            {
                // Download without timeout 
                process.WaitForExit();
                // Dunno if this makes sense ?
                outputWaitHandle.WaitOne();
                errorWaitHandle.WaitOne();
                processSuccess = true;
            }
            else
            { 
                processSuccess = 
                 process.WaitForExit(timeout) && 
                 outputWaitHandle.WaitOne(timeout) && 
                 errorWaitHandle.WaitOne(timeout);;
            }

`

**Comment by steffensiebert** [comment]
@bumbummen99 sorry man, but your commit is not working again. Do u use a IDE like VS-Studio or are you using notepad++ for editing your code? No front but this commit leads to a compile error. You can not chain void calls with a &&. Please use my code above to fix this.

**Comment by bumbummen99** [comment]
> @bumbummen99 sorry man, but your commit is not working again. Do u use a IDE like VS-Studio or are you using notepad++ for editing your code? No front but this commit leads to a compile error. You can not chain void calls with a &&. Please use my code above to fix this.

No doing this over the web ui as i am currently working on something entirely different and i have no time to make the build work rn. However you can spin up a PR into this PR if you need it immediately

**Pull request merged**
