### PR TITLE
Update index databases

### PR DESCRIPTION
**Pull request by LeonSt3**
Also added "SOUTH PARK THE 25TH ANNIVERSARY CONCERT" as S0E1 for english database

### CODE REVIEW

**Comment by PPrzemko** [comment]
Found some problems in release.

**Comment by Mantarochen01** [comment]
Hey @PPrzemko just saw your 1.75 Hotfix. Thanks for fixing the project. I think you uploaded the wrong file tho. It's way too small, and when opening the .exe the command line pops up for a second and then closes again. 

Merging your hotfix with version 1.74 data doesn't work either. 

Would be great if you could fix that. 

Greetings :).

**Comment by bumbummen99** [comment]
> Hey @PPrzemko just saw your 1.75 Hotfix. Thanks for fixing the project. I think you uploaded the wrong file tho. It's way too small, and when opening the .exe the command line pops up for a second and then closes again.
> 
> Merging your hotfix with version 1.74 data doesn't work either.
> 
> Would be great if you could fix that.
> 
> Greetings :).

Both files show normal size for me. Where did you get the files?
https://github.com/PPrzemko/southparkdownloader/blob/update-index-databases/docs/deutsch.db
https://github.com/PPrzemko/southparkdownloader/blob/update-index-databases/docs/english.db

**Comment by Mantarochen01** [comment]
@bumbummen99 Hey, I was refering to the 1.75 Hotfix ZIP as a whole. 
It's just ~360KB in size in comparison to the ~30 MB of your 1.74 Hotfix ZIP. 

Didn't find any other place to comment that, sorry if I used the wrong thread .

https://github.com/PPrzemko/southparkdownloader/releases/download/1.7.5/01_SouthParkDLCommandLine-1.7.5-win-x64.zip

**Comment by bumbummen99** [comment]
> @bumbummen99 Hey, I was refering to the 1.75 Hotfix ZIP as a whole. It's just ~360KB in size in comparison to the ~30 MB of your 1.74 Hotfix ZIP.
> 
> Didn't find any other place to comment that, sorry if I used the wrong thread .
> 
> https://github.com/PPrzemko/southparkdownloader/releases/download/1.7.5/01_SouthParkDLCommandLine-1.7.5-win-x64.zip

Yeah, he did not build it using the automated GitHub Action. He will have to use the Action to do the build or simply create a PR for the repo so it can build once i tag a new release.

**Comment by LeonSt3** [comment]
Somehow I accidentally aborted the build. Thanks. 
I tested this release(win-cli) on 2 PCs and had no problems. If you have any issues please report them. 
If I find the time, I'll do some more refactoring.

**Comment by bumbummen99** [comment]
> Somehow I accidentally aborted the build. Thanks. I tested this release(win-cli) on 2 PCs and had no problems. If you have any issues please report them. If I find the time, I'll do some more refactoring.

Thanks for your work buddy :) Make sure to create a draft PR for the code so others can chime in and help with reviewing the changes.

**Pull request merged**
